M48
; DRILL file {KiCad 7.0.6} date Wed 09 Aug 2023 14:49:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-09T14:49:31+09:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X111.0Y-145.0
X133.0Y-112.5
T2
X111.0Y-125.0
X113.0Y-112.5
T0
M30
